---
# User needs to supply -e receptor_bin=<location to built receptor executable>
- hosts: automationcontroller,execution_nodes
  vars:
    # ansible_user: ec2-user
    remote_receptor_loc: /usr/bin/receptor
  tasks:
    - name: Stop the receptor service
      systemd:
        name: receptor
        state: stopped
      become: true

    - name: Copy receptor binary
      ansible.builtin.copy:
        src: "{{ receptor_bin }}"
        dest: "{{ remote_receptor_loc }}"
        force: true
        owner: root
        group: root
        mode: '0755'
      become: true

    - name: Start the receptor service
      systemd:
        name: receptor
        state: started
        enabled: true
      become: true

    - name: Obtain the resultant receptor version
      command: receptor --version
      tags: version
      register: result

    - name: Debug the resultant receptor version
      debug:
        msg: "{{ result.stdout + '\n\n' + result.stderr }}"
      tags: version

- hosts: automationcontroller
  tasks:
    - name: Restart controller services for good measure
      shell: supervisorctl restart tower-processes:*
      become_user: awx
      become: true
