---
- hosts: automationcontroller
  gather_facts: false
  connection: local
  vars_files:
    - vars/private_vars.yml
  tasks:
    - name: Assure Default organization exists
      awx.awx.organization:
        name: Default
        tower_host: "{{ controller_base_url }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: false
      run_once: true

    - name: create test playbooks project
      awx.awx.project:
        name: test-playbooks
        organization: Default
        scm_url: https://github.com/ansible/test-playbooks.git
        scm_type: git
        tower_host: "{{ controller_base_url }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: false
      run_once: true

    - name: assure demo inventory exists
      awx.awx.inventory:
        name: Demo Inventory
        organization: Default
        tower_host: "{{ controller_base_url }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: false
      run_once: true

    - name: create a sleep playbook
      awx.awx.job_template:
        name: test-playbooks sleep.yml
        project: test-playbooks
        playbook: sleep.yml
        allow_simultaneous: true
        inventory: Demo Inventory
        tower_host: "{{ controller_base_url }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: false
      run_once: true

    - name: create a debug playbook
      awx.awx.job_template:
        name: test-playbooks debug.yml
        project: test-playbooks
        playbook: debug.yml
        allow_simultaneous: true
        inventory: Demo Inventory
        tower_host: "{{ controller_base_url }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: false
      run_once: true

    - name: create a noisy playbook
      awx.awx.job_template:
        name: test-playbooks chatty_tasks.yml
        project: test-playbooks
        playbook: chatty_tasks.yml
        allow_simultaneous: true
        inventory: Demo Inventory
        tower_host: "{{ controller_base_url }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        validate_certs: false
      run_once: true
