---
- name: Set awx-manage executable for development environment
  set_fact:
    awx_manage: /usr/local/bin/awx-manage
  when: ansible_connection == 'community.docker.docker'

- name: Create superuser without password
  shell: >
    {{ awx_manage }} createsuperuser
    --username={{ awx_username | quote}}
    --email={{ awx_email | quote }} --noinput
  register: result
  changed_when: "'That username is already taken' not in result.stderr"
  failed_when: >
    'That username is already taken' not in result.stderr and
    'Superuser created successfully' not in result.stdout
  become_user: awx
  become: true
  run_once: true

- name: Set the superuser password (set in private_vars.yml)
  shell: >
    {{ awx_manage }} update_password
    --username={{ awx_username }}
    --password={{ awx_password }}
  become_user: awx
  become: true
  register: result
  changed_when: "'Password updated' in result.stdout"
  run_once: true
