---
- name: Set settings file and supervisorctl for development environment
  set_fact:
    settings_loc: /etc/tower/conf.d/local_settings.py
    supervisorctl_exc: /usr/local/bin/supervisorctl
  when: ansible_connection == 'community.docker.docker'

- name: Change cleanup paths setting
  ansible.builtin.lineinfile:
    path: "{{ settings_loc }}"
    state: "{{ debug_state | default('present') }}"
    line: 'AWX_CLEANUP_PATHS = False'
    create: false
    # you might use these params for file creation, but that is dangerous, do not do it
    # mode: '0640'
    # group: awx
    # owner: root
    unsafe_writes: true
  become: true

- name: Change cleanup paths setting
  ansible.builtin.lineinfile:
    path: "{{ settings_loc }}"
    state: "{{ debug_state | default('present') }}"
    line: 'RECEPTOR_RELEASE_WORK = False'
    unsafe_writes: true
  become: true

- name: restart services
  shell: "{{ supervisorctl_exc }} restart tower-processes:*"
  become_user: awx
  become: True
